### ISSUE TITLE
2022-12-09

### ISSUE THREAD

**Issue by dannisword** [dannisword/itri#3]
## 文件變更
- [ ] A3-18 查詢單據照片 
- [ ] A1-8更新左側 前端要依當前模式去限制可進入的選單
- [ ] A1-23說明有改
- [ ] A1-47的參數名稱有改，wotkStn改成workStn
- [ ] A1-51在A1-站點管理V2文件裡，主要用來跳頁前檢查該站是否有執行中的單若還有執行中的單則不能跳頁

**Comment by dannisword** [comment]
測試結果
- [ ] 入庫單加總的入庫數量不對
![截圖 2022-12-08 下午1 49 08](https://user-images.githubusercontent.com/5735737/206624543-3541bdc3-7465-4ba7-83e9-a037bec8b127.png)

- [ ]  出庫單明細進不去

**Comment by yanghj366** [comment]
首頁 itri logo 拿掉

**Comment by yanghj366** [comment]
- [ ] 首頁itri logo拿掉
- [ ]  瀏覽器分頁的說明，「特奈第」改成「特耐第」
- [ ]  入庫的圖片，改成1個料品號只會有1張，所以準備中的圖片只需顯示1張。
